---
- name: Add PHP PPA Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/php

- name: Install PHP 7.0
  sudo: yes
  apt: pkg=php7.0-fpm state=present

- name: Install PHP Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: "{{ php_packages }}"

- include: configure.yml