- name: Set development domain
  lineinfile: dest=/etc/hosts state=present line="127.0.0.1 ansible.davidcorto.es"

- name: Set environment variables
  template: dest=/etc/environment src=environment

- name: Install composer dependencies
  become: yes
  become_user: vagrant
  composer: working_dir=/vagrant optimize_autoloader=yes no_dev=no
  environment:
      DATABASE_HOST: "{{ database_host }}"
      DATABASE_PORT: "{{ database_port }}"
      DATABASE_NAME: "{{ database_name }}"
      DATABASE_USER: "{{ database_user }}"
      DATABASE_PASSWORD: "{{ database_password }}"
      MAILER_HOST: "{{ smtp_host }}"
      MAILER_PORT: "{{ smtp_port }}"